export const types = {
    START_SPINNING:       'START_SPINNING',
    STOP_SPINNING:        'STOP_SPINNING',
    EMIT_ERROR:           'EMIT_ERROR',
    UPDATE_TASKS_FILTER:  'UPDATE_TASKS_FILTER',
    START_EDITING_TASK:   'START_EDITING_TASK',
    RESET_EDITING_TASK:   'RESET_EDITING_TASK',
    CONFIRM_EDITING_TASK: 'CONFIRM_EDITING_TASK',
    UPDATE_TASK_MESSAGE:  'UPDATE_TASK_MESSAGE',
};
